### ISSUE TITLE
Something wrong with the function init_prefix_table()

### ISSUE THREAD

**Issue by Range0122** [n2yen/KMP#1]
When text = "aabaaabaaac", pattern ="aabaaac", kmp return the result = -1, but it's obvious that the text is matched with the pattern. And I found something wrong with the function init_prefix_table:

`        
for i in range(1, len(word)):
    if word[i] == word[prefix_count]:
        prefix_count+=1
    else:
        prefix_count = 0
    prefix_table[i] = prefix_count
return prefix_table
`

For example, setting pattern ="aabaaac", when we run to the last letter 'a', and we'll compare it with the third letter 'b' since the first two letters of 'aab' is matched with 'aaa'. According to your code, we'll set prefix_count to 0, and prefix_table[i] will be 0, and the error happends here. Actually, we should set prefix_count to 2 because the last two letters of 'aaa' is still matched with the first two letters of the pattern.

**Comment by n2yen** [comment]
Thanks for the finding this. You're right, I'm double checking and will update.

**Comment by Range0122** [comment]
```
def kmp(text, pattern):
    def init_prefix_table(word):
        prefix_table = [0] * (len(word) + 1)
        prefix_table[0] = -1
        i, j = 0, -1
        while i < len(word):
            if j == -1 or word[i] == word[j]:
                i += 1
                j += 1
                prefix_table[i] = j
            else:
                j = prefix_table[j]

        return prefix_table[1:]

    prefix_table = init_prefix_table(pattern)
    pattern_index = 0

    for text_index, text_ch in enumerate(text):
        while pattern_index > 0 and text_ch != pattern[pattern_index]:
            pattern_index = prefix_table[pattern_index - 1]
        if text_ch == pattern[pattern_index]:
            if pattern_index == len(pattern) - 1:
                return text_index - pattern_index
            pattern_index += 1

    return -1
```

The new function `init_prefix_table(word)` works, you can check it. Hope it's helpful ~ :)

**Comment by n2yen** [comment]
thanks for the fix @Range0122! python script has been updated!
